# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88928b553e295756b94a09e827ffecdb384cf056c22ae14309cbbc208794965b4d915e6dc2df0b331085de5bddbd59e1645fd9fe4c99be21e6c30ed753cd46df

test:
  secret_key_base: 9ea94ad77427e77b1c0b0d4e7e382e35bc4c1e300c5ecef65af739a88eb7abc931f1063eb1f2d94e88fac9b52b648dfed47550fa59921c875ee5ad32536590c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
